version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: button_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: flask_app
    restart: always
    build: .
    image: test_webapp:latest
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: button_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    ports:
      - 5000:5000

volumes:
  postgres_data: